name: ject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.1
  flutter_image_compress: ^2.0.3
  path_provider: ^2.1.2
  image: ^3.0.1
  flutter_spinkit: ^5.2.1
  flip_card: ^0.7.0
  carousel_slider: ^5.0.0
  animations: ^2.0.11
  google_fonts: ^6.2.1
  lottie: ^3.2.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     # Ensure this directory contains ZenDots-Regular.ttf


